/*
* Copyright (c) 2000-2015  Samsung Electronics Co., Ltd All Rights Reserved
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
* http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*
*/

#ifndef __IVUG_STRING_H__
#define __IVUG_STRING_H__

#include <libintl.h>
#include <app.h>
#include "ivug-define.h"


static inline char * ivug_get_resource_path() {
	char * path = app_get_resource_path();
	return path;
}

static inline char* full_path(const char *str1, const char *str2) {
	char path[1024] = {};
	snprintf(path, 1024, "%s%s", str1, str2);
	char *full_path = strdup(path);
	return full_path;
}


#define UG_RES_PATH 		ivug_get_resource_path()

#define LOCALE_PATH 					full_path(UG_RES_PATH, "locale")
/* Original code is in appcore-common.h */
#define gettext_noop(str) (str) /**< keyword for xgettext  to extract translatable strings */
#define N_(str) gettext_noop(str)  /**< gettext_noop alias */

#define GET_IDS_COM(id) (dgettext("sys_string", (id)))
#define GET_IDS(id) (dgettext(IVUG_TEXT_DOMAIN, (id)))

#ifndef PACKAGE
#error PACKAGE is not defined
#endif

#ifndef LOCALE_PATH
#error LOCALE_PATH is not defined
#endif

//string
#define IVUG_TEXT_DOMAIN "image-viewer"
#define IVUG_LOCALEDIR LOCALE_PATH

/***********************************************/
/* String has to be sorted in ascending order. */
/***********************************************/

// Not yet translated
#define IDS_SHARE_AS_VIDEO "IDS_IV_OPT_AS_VIDEO_FILES"
#define IDS_SHARE_AS_IMAGE "IDS_IV_OPT_AS_IMAGE_FILES"
#define IDS_SHARE_AS "IDS_IV_OPT_SHARE"//"IDS_IV_HEADER_SHARE_SOUND_N_SHOT_PICS_ABB"	//cannot show & at efl

#define IDS_HIDDEN "Hidden"

#define IDS_SELECT_CONTACT "IDS_IV_HEADER_SELECT_CONTACT_TO_SHARE"

#define IDS_PLAY_SPEED "IDS_IV_HEADER_PLAY_SPEED"
#define IDS_PLAY_SPEED_1_5TH "x1/5"
#define IDS_PLAY_SPEED_1_2TH "x1/2"
#define IDS_PLAY_SPEED_1 "x1"
#define IDS_PLAY_SPEED_2 "x2"

#define IDS_UNKOWN_FORMAT "IDS_IV_POP_FILE_FORMAT_NOT_SUPPORTED"

#define IDS_PROCESSING "Processing..."

#define IDS_DO_NOT_TAGBUDDY_DESCRIPTION _("Enanble auto refresh in weather widget to view weather tags</br></br>Enable GPS tags in Camera to view location tags</br></br>Tap faces to view infomation about the people")

#define IDS_NEARBY_DESCRIPTION "IDS_IV_POP_VIEW_YOUR_MEDIA_ON_OTHER_DEVICES_USING_NEARBY_DEVICES"

#define IDS_COLLABORATIVE_PLAY _("Collaborative play")

#define IDS_CALLER_ID_DESCRIPTION "IDS_IV_POP_SET_THIS_PICTURE_AS_PSS_CALLER_ID_Q"

#define IDS_FLASH_ON 			"IDS_CAM_BODY_FLASH_ON"
#define IDS_FLASH_OFF 			"IDS_CAM_BODY_FLASH_OFF"
#define IDS_DURATION_PLAY		"IDS_MP_BODY_DURATION"
#define IDS_SET_POP				"IDS_ST_POP_SET"
#define IDS_FACE_TAG			"IDS_PBR_POP_FACE_TAG"

#define IDS_SELECT_PICTURE		"IDS_MEDIABR_BODY_SELECT_PICTURE"
#define IDS_ALL_PICTURES		"IDS_MEDIABR_OPT_ALL_PICTURES"
#define IDS_ADD_TO_HOME			"IDS_MEDIABR_SK2_ADD_TO_HOME"
#define IDS_EDIT_IMAGE			"IDS_MEDIABR_OPT_EDIT_IMAGE"

#define IDS_DYNAMIC_BOX			_("Dynamic Box")
#define IDS_MMS					_("MMS")
#define IDS_INVALID_NAME		"IDS_COM_POP_INVALID_CHARACTERS"//_("Invalid name")
#define IDS_CLOUD				"IDS_IV_OPT_CLOUD"
#define IDS_GROUP_PLAY			_("Group play")
#define IDS_RENAME				"IDS_COM_SK_RENAME"
#define IDS_CREATE_ALBUM		_("Create album")

#define IDS_CANNOT_LOAD_FILE_LST	_("Cannot load file list")

#define IDS_NULL				_("")

#define IDS_WIFI_DIRECT			_("Wi-Fi Direct")

#define IDS_ORIENTATION 		"IDS_MEDIABR_HEADER_ORIENTATION"
#define IDS_MANUFACTURE 		"IDS_IV_BODY_MANUFACTURER"
#define IDS_MODEL				"IDS_IV_BODY_MODEL"
#define IDS_FLASH 				"IDS_CAM_BODY_FLASH"
#define IDS_DURATION			"IDS_IV_BODY_DURATION"
#define IDS_FOCAL_LENGTH 		"IDS_CAM_BODY_FOCAL_LENGTH"
#define IDS_WHITE_BALANCE		"IDS_IV_BODY_WHITE_BALANCE"
#define IDS_AUTO				"IDS_IV_BODY_AUTO"
#define IDS_MANUAL				"IDS_COM_BODY_MANUAL"
#define IDS_APERTURE 			"IDS_IV_BODY_APERTURE"
#define IDS_EXPOSURE_TIME 		"IDS_IV_BODY_EXPOSURE_TIME_ABB"
#define IDS_ISO 				"IDS_CAM_BODY_ISO"

#define IDS_NO_TAG	                "IDS_IV_BODY_NO_TAG"
#define IDS_SUNNY_DAY	            "IDS_IV_BODY_SUNNY_DAY"
#define IDS_CLOUDY_DAY	            "IDS_IV_BODY_CLOUDY_DAY"
#define IDS_RAINY_DAY	            "IDS_IV_BODY_RAINY_DAY"
#define IDS_SNOWY_DAY	            "IDS_IV_BODY_SNOWY_DAY"
#define IDS_CLEAR_NIGHT	           	"IDS_IV_BODY_CLEAR_NIGHT"
#define IDS_IN                 		"IDS_IV_BODY_IN"
#define IDS_WITH					_("With")

#define IDS_TAG_BUDDY_ACCESS_TEXT1	"IDS_IV_BODY_ENABLE_AUTO_REFRESH_IN_THE_WEATHER_WIDGET_TO_SEE_WEATHER_TAGS"
#define IDS_TAG_BUDDY_ACCESS_TEXT2	"IDS_IV_BODY_ENABLE_GPS_TAGS_IN_CAMERA_TO_SEE_LOCATION_TAGS"
#define IDS_TAG_BUDDY_ACCESS_TEXT3	"IDS_IV_BODY_TAP_FACES_TO_VIEW_INFORMATION_ABOUT_THE_PEOPLE"

#define IDS_WALLPAPER_NOTIFY	"IDS_IV_BODY_SELECTED_AREA_WILL_BE_APPLIED_TO_THE_WALLPAPER"
#define IDS_CROP_NOTIFY			"IDS_IV_BODY_SELECT_AN_AREA_TO_CROP_THE_PICTURE"
#define IDS_CALLER_ID_NOTIFY	"IDS_IV_BODY_SELECTED_AREA_WILL_BE_APPLIED_TO_THE_CONTACT_PICTURE"
#define IDS_PRINT_NOTIFY		"IDS_IV_BODY_SELECTED_AREA_WILL_BE_PRINTED"

#define IDS_ALLSHARE_NOTIFY		"IDS_IV_BODY_YOU_CAN_SHARE_YOUR_MEDIA_WITH_OTHER_DEVICES_USING_NEARBY_DEVICES"

/* Registered string in STMS IV */
#define IDS_ACCUMULATED_TIME 	"IDS_IV_ACCUMULATED_TIME"
#define IDS_ADD_CAPTION			"IDS_IV_OPT_ADD_CAPTION"
#define IDS_ADD_COMMENT			"IDS_IV_SK3_ADD_COMMENT"
#define IDS_ADD_NAME			"IDS_IV_OPT_ADD_NAME_ABB"
#define IDS_ADD_TAG				"IDS_IV_HEADER_ADD_TAG"
#define IDS_ADD_WEATHER_TAG		"IDS_IV_OPT_ADD_WEATHER_TAG_ABB"
#define IDS_ADDED				"IDS_IV_POP_ADDED"
#define IDS_ALL_ALBUMS			"IDS_IV_HEADER_ALL_ALBUMS"
#define IDS_ANY 				"IDS_IV_BODY_ANY"
#define IDS_AVAILABLE_USES 		"IDS_IV_BODY_AVAILABLE_USES"
#define IDS_BASIC 				"IDS_IV_BODY_BASIC"
#define IDS_BUDDY_PHOTO_SHARE	"IDS_IV_OPT_BUDDY_PHOTO_SHARE"
#define IDS_CALLER_IMAGE		"IDS_IV_BODY_CALLER_IMAGE"
#define IDS_CONNECTION_INFO		"IDS_IV_OPT_CONNECTION_INFO_ABB"
#define IDS_COPY_TO_CLIPBOARD	"IDS_IV_OPT_COPY_TO_CLIPBOARD"
#define IDS_COPY				"IDS_CAM_POP_COPY"
#define IDS_COUNT 				"IDS_IV_BODY_COUNT"
#define IDS_CREATE_TAG			"IDS_IV_BODY_CREATE_TAG"
#define IDS_CROP 				"IDS_IV_BODY_CROP"
#define IDS_DATE_CREATED 		"IDS_IV_BODY_DATE_CREATED"
#define IDS_DISPLAY 			"IDS_IV_BODY_DISPLAY"
#define IDS_DO_NOT_ASK_AGAIN	"IDS_IV_BODY_DONT_ASK_AGAIN"
#define IDS_DO_NOT_SEND			"IDS_IV_BODY_DO_NOT_SEND"
#define IDS_EDIT_CAPTION		"IDS_IV_OPT_EDIT_CAPTION"
#define IDS_EDIT_TAG			"IDS_IV_OPT_EDIT_TAG"
#define IDS_EDIT_WEATHER_TAG	"IDS_IV_OPT_EDIT_WEATHER_TAG_ABB"
#define IDS_ENTER_TAG_NAME  	"IDS_IV_POP_ENTER_TAG_NAME"
#define IDS_ENTRY_IS_EMPTY 		"IDS_IV_POP_ENTRY_IS_EMPTY"
#define IDS_EXECUTE 			"IDS_IV_BODY_EXECUTE"
#define IDS_FORMAT 				"IDS_IV_BODY_FILE_FORMAT"
#define IDS_FILE_LOCATION 		"IDS_IV_BODY_FILE_LOCATION"
#define IDS_FILE_SIZE_IS_TOO_SMALL	"IDS_IV_POP_THE_IMAGE_IS_TOO_SMALL"
#define IDS_FILE_TRANSFER		"IDS_IV_OPT_FILE_TRANSFER"
#define IDS_FORWARDING 			"IDS_IV_BODY_FORWARDING"
#define IDS_GET_DIRECTIONS		"IDS_IV_OPT_GET_DIRECTIONS_ABB"
#define IDS_HOME_AND_LOCK_SCREEN_WALLPAPER "IDS_IV_OPT_HOME_AND_LOCK_SCREEN_WALLPAPER"
#define IDS_HOME_AND_LOCK_SCREENS "IDS_IV_BODY_HOME_AND_LOCK_SCREENS"
#define IDS_HOME_SCREEN			"IDS_IV_BODY_HOME_SCREEN"
#define IDS_HOME_SCREEN_WALLPAPER "IDS_IV_HEADER_HOME_SCREEN_WALLPAPER_ABB"
#define IDS_IMPOSSIBLE 			"IDS_IV_BODY_IMPOSSIBLE"
#define IDS_INDIVIDUAL 			"IDS_IV_BODY_INDIVIDUAL"
#define IDS_INTERVAL 			"IDS_IV_BODY_INTERVAL"
#define IDS_INVALID_IMAGE_FILE	"IDS_IV_POP_INVALID_IMAGE_FILE"
#define IDS_LATITUDE 			"IDS_IV_BODY_LATITUDE"
#define IDS_LOCATION 			"IDS_IV_BODY_LOCATION_ABB2"
#define IDS_LOCATION_PATH		"IDS_IV_BODY_LOCATION_M_PATH"
#define IDS_LOCK_SCREEN			"IDS_IV_BODY_LOCK_SCREEN"
#define IDS_LOCK_SCREEN_WALLPAPER "IDS_IV_HEADER_LOCK_SCREEN_WALLPAPER_ABB"
#define IDS_LONGITUDE 			"IDS_IV_BODY_LONGITUDE"
#define IDS_NO_FACE_DETECTED	"IDS_IV_POP_NO_FACES_HAVE_BEEN_TAGGED_TAG_FACES_IN_THE_PICTURE"
#define IDS_MANUALLY_DETECT		"IDS_IV_OPT_MANUALLY_DETECT"
#define IDS_MAX_CHAR_LENGTH_REACHED "IDS_IV_POP_MAXIMUM_NUMBER_OF_CHARACTERS_HPD_REACHED"
#define IDS_ME					"IDS_IV_BODY_ME"
#define IDS_MY_DEVICE           "IDS_IV_BODY_MY_DEVICE"
#define IDS_N_A 				"IDS_IV_BODY_N_A"
#define IDS_NEAR_DEVICES		"IDS_IV_BODY_NEARBY_DEVICES_T_ALLSHARE"
#define IDS_NEW_TAG				"IDS_IV_BODY_NEW_TAG"
#define IDS_NO_TAGGED_FACE	"IDS_IV_POP_NO_FACES_HAVE_BEEN_TAGGED_TAG_FACES_IN_THE_PICTURE"
#define IDS_PEOPLE				"IDS_IV_BODY_PEOPLE"
#define IDS_PERMISSION_DENIED 	"IDS_IV_POP_PERMISSION_DENIED"
#define IDS_POSSIBLE 			"IDS_IV_BODY_POSSIBLE"
#define IDS_PRINT 				"IDS_IV_BODY_PRINT"
#define IDS_PRINT_VIA_BLUETOOH	"IDS_IV_OPT_PRINT_VIA_BLUETOOTH"
#define IDS_REFRESH				"IDS_IV_OPT_REFRESH"
#define IDS_REMOVE_TAG			"IDS_IV_OPT_REMOVE_TAG"
#define IDS_RESOLUTION 			"IDS_IV_BODY_RESOLUTION"
#define IDS_RIGHT_STATUS 		"IDS_IV_BODY_RIGHT_STATUS"
#define IDS_ROTATE_LEFT 		"IDS_IV_OPT_ROTATE_LEFT"
#define IDS_ROTATE_RIGHT 		"IDS_IV_OPT_ROTATE_RIGHT"
#define IDS_SD_CARD_REMOVED		"IDS_IV_POP_SD_CARD_REMOVED"
#define IDS_SELECT_DEVICE		"IDS_IV_POP_SELECT_DEVICE"
#define IDS_SEND_PICTURE_TO		"IDS_IV_HEADER_SEND_PICTURE_TO_ABB"
#define IDS_SERVER_NAME 		"IDS_IV_BODY_SERVER_NAME"
#define IDS_SET_AS				"IDS_IV_OPT_SET_AS"
#define IDS_SET_AS_CALLER_ID	"IDS_IV_POP_SET_AS_CALLER_ID_M_PAST_TENSE"
#define IDS_SET_WALLPAPER_FOR_HOME_SCREEN_AND_LOCK_SCREEN "IDS_IV_POP_SET_WALLPAPER_FOR_HOME_SCREEN_AND_LOCK_SCREEN"
#define IDS_SHARE		  		"IDS_IV_OPT_SHARE"
#define IDS_SHARE_VIA			"IDS_IV_BODY_SHARE_VIA"
#define IDS_SLIDE_SHOW			"IDS_IV_OPT_SLIDESHOW_ABB"	//"IDS_IV_OPT_SLIDE_SHOW" -> slide show
#define IDS_FILE_DOWNLOAD		"IDS_IV_OPT_DOWNLOAD"
#define IDS_DELETE_IMAGE		"IDS_IV_OPT_DELETE_ABB"
#define IDS_RENAME_IMAGE		"IDS_IV_OPT_RENAME"
#define IDS_DELETE_IMAGE_MESSAGE	"IDS_IV_POP_THIS_IMAGE_WILL_BE_DELETED"
#define IDS_DELETE_VIDEO_MESSAGE	"IDS_VIDEO_POP_THIS_VIDEO_WILL_BE_DELETED"
#define IDS_RENAME_BUTTON		"IDS_IV_BUTTON_RENAME_ABB"
#define IDS_RENAME_FILE_EXIST	"IDS_VIDEO_TPOP_FILE_NAME_ALREADY_IN_USE"
#define IDS_SLIDESHOW_STOP		"IDS_IV_BUTTON_STOP"
#define IDS_SLIDESHOW_SLIDE_INTERVAL	"IDS_IV_HEADER_SLIDE_INTERVAL_ABB"
#define IDS_SLIDESHOW_EFFECT	"IDS_IV_BODY_EFFECT"
#define IDS_SLIDESHOW_FADE_EFFECT	"IDS_IV_OPT_FADE_M_EFFECT"
#define IDS_SLIDESHOW_FLOW_EFFECT	"IDS_DFRAME_BODY_FLOW_M_EFFECT"
#define IDS_SLIDE_SECOND		"IDS_COM_BODY_1_SECOND"
#define IDS_SLIDE_SECONDS		"IDS_COM_BODY_PD_SECONDS"
#define IDS_TAG			 		"IDS_IV_OPT_TAG"
#define IDS_TAGBUDDY            "IDS_IV_OPT_TAG_BUDDY"
#define IDS_TIMED_COUNT 		"IDS_IV_BODY_TIMED_COUNT"
#define IDS_TRIM				"IDS_IV_OPT_TRIM"
#define IDS_UNABLE_TO_OPEN_FILE	"IDS_IV_POP_UNABLE_TO_OPEN_FILE"
#define IDS_UNLIMITED 			"IDS_IV_BODY_UNLIMITED"
#define IDS_USE_MOTION 			"IDS_IV_OPT_USE_MOTION"
#define IDS_VALIDITY 			"IDS_IV_BODY_VALIDITY"
#define IDS_VENDOR 				"IDS_IV_BODY_VENDOR"
#define IDS_WEATHER				"IDS_IV_BODY_WEATHER"
#define IDS_WRITE_CAPTION		"IDS_IV_OPT_WRITE_CAPTION"

#define IDS_PD_SELECTED 		"IDS_GALLERY_HEADER_PD_SELECTED_ABB"


// System string.
#define IDS_BLUETOOTH 		"IDS_COM_BODY_BLUETOOTH"
#define IDS_EMAIL 			"IDS_COM_BODY_EMAIL"
#define IDS_S_NOTE 			"IDS_COM_BODY_S_NOTE"
#define IDS_S_MEMO			"IDS_COM_OPT_S_MEMO"
#define IDS_MESSAGE 		"IDS_COM_BODY_MESSAGE"
#define IDS_WI_FI			"IDS_COM_BODY_WI_FI"
#define IDS_NFC				"IDS_COM_BODY_NFC"

#define IDS_FACEBOOK 		"IDS_COM_BODY_FACEBOOK"
#define IDS_PICASA  		"IDS_COM_BODY_PICASA"
#define IDS_TWITTER 		"IDS_COM_BODY_TWITTER"

#define IDS_ALLSHARE		"IDS_COM_BODY_ALLSHARE"
#define IDS_APPLICATION_NOT_INSTALLED "IDS_COM_BODY_APPLICATION_NOT_INSTALLED"
#define IDS_BACK 			"IDS_COM_BODY_BACK"
#define IDS_CANCEL 			"IDS_COM_SK_CANCEL"
#define IDS_CLOSE 			"IDS_COM_BODY_CLOSE"
#define IDS_CHANGE_NAME		"IDS_COM_BODY_CHANGE_NAME"
#define IDS_COPY			"IDS_COM_BODY_COPY"
#define IDS_COPIED_TO_CLIPBOARD		"IDS_COM_POP_COPIED_TO_CLIPBOARD"
#define IDS_DATE			"IDS_COM_BODY_DATE"
#define IDS_DETAILS			"IDS_COM_BODY_DETAILS"
#define IDS_DELETE_MSG		"IDS_COM_POP_DELETE_Q"
#define IDS_DELETE 			"IDS_IV_OPT_DELETE_ABB"
#define IDS_DELETED 		"IDS_COM_POP_DELETED"
#define IDS_DONE 			"IDS_COM_SK_DONE"
#define IDS_DOWNLOAD 		"IDS_COM_SK_DOWNLOAD"
#define IDS_DOWNLOAD_FAILED	"IDS_COM_POP_DOWNLOAD_FAILED"
#define IDS_EDIT			"IDS_COM_BODY_EDIT"
#define IDS_ENTER_NAME		"IDS_COM_BODY_ENTER_NAME"
#define IDS_ERROR			"IDS_COM_POP_ERROR"
#define IDS_FAILED 			"IDS_COM_POP_FAILED"
#define IDS_FAVOURITE		"IDS_COM_BODY_FAVOURITE"
#define IDS_FAVOURITES		"IDS_COM_BODY_FAVOURITES"
#define IDS_LOADING 		"IDS_COM_BODY_LOADING"
#define IDS_MAXIMUM_NUMBER_OF_CHARACTERS_REACHED		"IDS_COM_POP_MAXIMUM_NUMBER_OF_CHARACTERS_REACHED"
#define IDS_MORE 			"IDS_COM_BODY_MORE"
#define IDS_MOVE			"IDS_COM_BODY_MOVE"
#define IDS_NAME 			"IDS_COM_BODY_DETAILS_NAME"
#define IDS_NO	 			"IDS_COM_SK_NO"
#define IDS_NO_NAME			"IDS_COM_BODY_NO_NAME"
#define IDS_OFF 			"IDS_COM_BODY_OFF"
#define IDS_OK 				"IDS_COM_SK_OK"
#define IDS_ON 				"IDS_COM_BODY_ON"
#define IDS_PLAY			"IDS_COM_SK_PLAY"
#define IDS_SAVE 			"IDS_COM_SK_SAVE"
#define IDS_SAVED 			"IDS_COM_POP_SAVED"
#define IDS_SEND			"IDS_COM_BODY_SEND"
#define IDS_SET				"IDS_COM_SK_SET"
#define IDS_SETTINGS		"IDS_COM_BODY_SETTINGS"
#define IDS_SIZE 			"IDS_COM_BODY_SIZE"
#define IDS_SUCCESS 		"IDS_COM_POP_SUCCESS"
#define IDS_SYSTEM			"IDS_COM_BODY_SYSTEM"
#define IDS_TIME 			"IDS_COM_POP_TIME"
#define IDS_TYPE 			"IDS_COM_POP_TYPE"
#define IDS_UNKNOWN 		"IDS_COM_BODY_UNKNOWN"
#define IDS_YES 			"IDS_COM_SK_YES"
#define IDS_CANCEL_CAPS		"IDS_TPLATFORM_ACBUTTON_CANCEL_ABB"
#define IDS_DONE_CAPS		"IDS_TPLATFORM_ACBUTTON_DONE_ABB"

#define IDS_B				_("B")
#define IDS_KB				"IDS_COM_BODY_KB"
#define IDS_MB				"IDS_COM_BODY_MB"
#define IDS_GB				_("GB")
#define IDS_SET_WEATHER_FAILED     _("Set Weather failed")

#define NO_WEATHER_INFO     _("No Info.")
#define RESERVED_WEATHER     _("Reserved")
#define SUNNY_WEATHER     _("Sunny")
#define CLOUDY_WEATHER     _("Cloudy")
#define RAINY_WEATHER    _("Rainy")
#define SNOWY_WEATHER     _("Snowy")
#define CLEAR_WEATHER     _("Clear")


#define IDS_HELP_SLIDE			"IDS_HELP_BODY_SCROLL_LEFT_OR_RIGHT_TO_VIEW_MORE_PICTURES"
#define IDS_HELP_PINCH_ZOOM_IN	"IDS_HELP_BODY_PINCH_OUT_TO_ZOOM_IN"
#define IDS_HELP_PINCH_ZOOM_OUT "IDS_HELP_BODY_PINCH_IN_TO_ZOOM_OUT"

#endif // __IVUG_STRING_H__


